cool_value: ENC[AES256_GCM,data:Chkl,iv:69TUH4r5/a8OvuMa8ae0gke0sc9s6sVnHt+JHfvA4Zg=,tag:ifwS6esm0m5qC539GE7pDw==,type:str]
other_value: ENC[AES256_GCM,data:8uzwnA==,iv:xdN8fLsJMapJaGnysU0elS0xNzrHvzfNZyyKG4qeKEM=,tag:skw5+73Mt5r6cSm40Qgp1Q==,type:bool]
nested_value:
    b: ENC[AES256_GCM,data:j2e+50Y=,iv:cBE9OUa2KwqShUsSjo9Av1Nt3MJI31XbadES59vGBeY=,tag:fmSSkvTQtNGIzXTLPt2TMg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-03-26T18:36:29Z'
    mac: ENC[AES256_GCM,data:VxymsQQ+w7u4gBeu6JE2rA0xXidgRNkE4YTmzMYfj6TeD97RcaOHxHrR79+7rVbzaJ+OLfWWSoBP8PfszEUj+K+nz01RInDJSILNIf7RyvIRI5L+HYXhfZmU63ibAvMZeNComhlR5WPctvXIlwx6+baT0qek1NEx+O9gelrsEY4=,iv:/pfoiwLAyNeS94lJdrYeXD6iMbjT5QJeEJuqUhppSuE=,tag:gOJene4f8IvmrxlFgO6TsQ==,type:str]
    pgp:
    -   created_at: '2020-03-26T18:26:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9YMrxfI31bvAQf/RKOxcjnExTSJUXQH3EEhxR9jTHcIKWgkVhY07yB/zYJR
            BFz0FrhyE9PpktDj49khSlE+wwtlywgbuWRJISyV3dkt1iX/gPgUpIEteJtMZ+4i
            SqjE53/E7tasBCawnG3pHQK1Tq3X+T/ULAvchbxNiHoc3F5P3ekpt8s5vPYbZbhv
            ESQsfWWTPI84oJy6/YtMHIzg5AyDgCtfKlaa45Vlvk9N85f2vjGlfCcqZH883Mjm
            FOJ1g5rliav6g8Kuetez4jSllrA3u9NHCnol8YNw6yTqGOF0UnlsMgwShv1x8SnW
            OeZQILjOq6QKm5K1EozMT2Y0ET16hf9/voPHoJqjydJeAZthLf8qH92dZ+khkCz4
            qzdZIucsyoPVLzNPnrYByOK9oy5krzGIEsikQwpmco0QlL1EpCD7nkd35CMLxaNk
            rKUW2XWW/EYppCdR6C3OVOGDJ2Rb9qoeuVXpkdjEAw==
            =z0oB
            -----END PGP MESSAGE-----
        fp: 5DA7055DCBB37598199225A0F9B9B9C44872CCE4
    -   created_at: '2020-03-26T18:27:05Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3QY2uF8+BG2AQf8DeEPL1nHbF1pI3RzLcDqR8mUz8A+azBIgCvhvXOreGH+
            i/K8TJvK+7nmfOZZK3ckY4vEKlrMoPIL/w3lxKA8jwNpTSMYf+sf6UQzvdifhrOb
            coJk681xY2/VWmCAkkH2LNg931nVuzY/ndk9y45Emf/wlOkPEynv3HuX8aWxAp17
            +z58v0hkzTwTdjzT4I+5UTwt2gSLLksrSsSZMN+bY0ljdczAxLsRDZTraIdTY/xt
            dbtQcGzAFLDX6yMp8mk7TCLiZoZQZdS6hDTtLprPb7nHV1UUtggHBdnG+FEjMJ0W
            nFJulz++6RfqFlR5MWV1X8lO9iwVsP41h02+cemlnNJeAZJ1zHYh8SLImC6JS2Ld
            GOer5c3J7Lukh/2Y+pWm0OEK2DNhHcy4ZSj9Oi3+8dxfBt9nnnMoeCHnVBai8Mnk
            xNzB99+Y72k2mlSHv1dF/Pzv/aAVfNDTTtFj31yBtQ==
            =JEF5
            -----END PGP MESSAGE-----
        fp: 8C2C80A722BD8CF9A03908B0339B09808BF1E8C3
    unencrypted_suffix: _unencrypted
    version: 3.5.0
